-- Autocmds are automatically loaded on the VeryLazy event
-- Default autocmds that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/autocmds.lua
--
-- Add any additional autocmds here
-- with `vim.api.nvim_create_autocmd`
--
-- Or remove existing autocmds by their group name (which is prefixed with `lazyvim_` for the defaults)
-- e.g. vim.api.nvim_del_augroup_by_name("lazyvim_wrap_spell")

--
-- vim.api.nvim_create_autocmd("BufWinEnter", {
--   group = vim.api.nvim_create_augroup("snacks_explorer_autorefresh", { clear = true }),
--   callback = function(event)
--     local picker = Snacks.picker.get({ source = "explorer" })[1]
--     if not picker or picker:cwd() == LazyVim.root() then
--       return
--     end
--     -- Variant 1: change directory
--     local A = require("snacks.explorer.actions")
--     pcall(function()
--       picker:set_cwd(vim.fn.expand("%:p:h"))
--       A.actions.explorer_update(picker)
--     end)
--     -- Variant 2: reveal the buffer/file
--     -- local E = require 'snacks.explorer'
--     -- E.reveal(event.buf)
--   end,
-- })
